project_name: uniclipboard

builds:
  - main: dummy.go
    goarch:
      - amd64
      - arm64
    binary: uniclipboard
    hooks:
      post: sh ./scripts/build-cross-release.sh
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64

archives:
  - format: binary
    builds_info:
      mode: 0755

nfpms:
  - id: uniclipboard
    package_name: uniclipboard
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    vendor: mkdir700
    homepage: https://github.com/mkdir700/uniclipboard
    maintainer: mkdir700 <mkdir700@gmail.com>
    description: A cross-platform clipboard sharing tool designed to create a seamless clipboard experience
    license: Apache-2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin

snapcrafts:
  - id: uniclipboard
    name: uniclipboard
    title: UniClipboard
    publish: false
    summary: A cross-platform clipboard sharing tool 
    description: |
      A cross-platform clipboard sharing tool designed to create a seamless clipboard experience
      across multiple devices.
    grade: stable
    confinement: strict
    license: Apache-2.0
    base: core20
    apps:
      uniclipboard:
        command: uniclipboard
        plugs: [network, network-bind, home, x11, wayland, desktop, desktop-legacy, unity7]
      # uniclipboard-daemon:
      #   command: uniclipboard
      #   daemon: simple
      #   plugs: plugs: [network, network-bind, home, x11, wayland, desktop, desktop-legacy, unity7]

release:
  draft: true
  replace_existing_draft: true
  replace_existing_artifacts: true
# changelog:
#   sort: asc
#   filters:
#     exclude:
#       - '^docs:'
#       - '^test:'
