project_name: uniclipboard

builds:
  - main: dummy.go
    goarch:
      - amd64
    goos:
      - windows
    binary: uniclipboard
    hooks:
      post:
        - powershell.exe -ExecutionPolicy Bypass -File .\scripts\replace-bin.ps1

archives:
  # 使用zip格式, 否则 goreleaser 会因为找不到 windows arch 而报错
  # 实际上，并不需要这个 zip 包，只是为了满足 goreleaser 的要求
  # download_url 会使用 binary 的 url
  - format: zip

chocolateys:
  - name: uniclipboard
    owners: mkdir700
    title: UniClipboard
    authors: mkdir700
    project_url: https://github.com/mkdir700/uniclipboard
    license_url: https://github.com/mkdir700/uniclipboard/blob/main/LICENSE
    project_source_url: https://github.com/mkdir700/uniclipboard
    docs_url: https://github.com/mkdir700/uniclipboard/blob/main/README.md
    bug_tracker_url: https://github.com/mkdir700/uniclipboard/issues
    tags: "clipboard sharing tool"
    summary: A cross-platform clipboard sharing tool designed to create a seamless clipboard experience
    description: |
      {{ .ProjectName }} installer package.
      UniClipboard is A cross-platform clipboard sharing tool  designed to create a seamless clipboard experience across multiple devices.
    release_notes: "https://github.com/mkdir700/uniclipboard/releases/tag/v{{ .Version }}"
    url_template: "https://github.com/mkdir700/uniclipboard/releases/download/{{ .Tag }}/{{ .Env.ARTIFACT_NAME }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    skip_publish: false

release:
  disable: true
